### ISSUE TITLE
Display and sorting of language lists

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2390]
This issue has been problematic for TED (and I believe a few other teams as well).

---Reported by Jenny Z----

URLs:
http://amara.org/en/profiles/edit/
http://amara.org/en/unisubservicesauth/ted_login/ (TED team application)

Observed:
An increasing number of new volunteers select incorrect languages at sign up because major language names have been localized, and thus appear at the bottom of the select menu. (Localized languages drop to the bottom of the list when they aren't capitalized, begin with a diacritic, or use a non-Latin script.) 

Because new applicants select language variants instead (like 'British English', which isn't a preferred TED language), these volunteers do not see any videos on their dashboard and therefore do not start subtitling. 

Each day, the TED team must manually message applicants who choose language variants to explain how to find and set their correct language.

Example: 
A new Spanish translator sets their language as ‘Argentinian Spanish’ because they didn't see 'español' at the bottom of the dropdown menu. The new translator's dashboard is empty because ‘Argentinian Spanish’ is not a TED-preferred language.

![-1](https://cloud.githubusercontent.com/assets/216145/10646425/06ff8c1c-7801-11e5-8404-102cfdd04802.png)

---Suggested Solutions---
Best practice, based on how Apple/Android seem to do it, is showing both english version of language (which could be localized in transifex) as well as the native script (would not be available for localization in transifex) for each language. May be nice if everything was title-cased, like example below:

![screen shot 2015-10-22 at 12 40 39 pm](https://cloud.githubusercontent.com/assets/216145/10671701/1e9a34e4-78ba-11e5-9f67-c78699a60d13.png)

For sorting, the simplest method might be alphabetical, based on ISO 639-1 and 639-2

**Comment by bendk** [comment]
One interesting thing I learned while implementing this is that title case is not consistent between languages.  So I would write "Spanish", but a native speaker would write "español".  I'm going to title case everything for when displaying it in the select boxes, but there's an argument for keeping the native casing.  If we went the alternate route, we should ignore case when sorting the list.

**Comment by bendk** [comment]
Another interesting thing is that the native names aren't unique.  Native speakers of Southern Ndebele and Northern Ndebele both call their language "isiNdebele" -- at least according to the babel package which uses the unicode consortium's database for language names.

I think that's okay in practice since the second string we'll list is the language translated into the language we're rendering the page in.  That second string will be unique.

**Comment by bendk** [comment]
The last thing to note is that the babel package we're using seems to 2 of our language codes as the same language:
  - aka (Akan)
  - tw (Twi)

I don't really understand what's going on here.  However, this means that if we only use the logic from babel, then those two language codes will be displayed exactly the same.  I'm going to make it so that we display tw as "Twi".

**Comment by bendk** [comment]
My last comment is that I'm pretty sure that I made it so the ordering done using the unicode collation algorithm.  I think this should be more correct, and it seems more correct to me, but I don't have any real knowledge on this issue.

**Comment by bendk** [comment]
And my last comment #2 is that we're using the babel library, which gets language names from the Unicode Common Locale Data Repository.

It seems that some of our languages are not listed in that repository (e.g. Abkhazian).  And some translations of languages are not listed (e.g. Southern Ndebele translated into North Ndebele).  For those cases, I made it so we use the old label, which is the translation of the language name using our transifex data.

**Comment by bendk** [comment]
This change contains a couple new libarries.  Run `dev build` before testing.

**Comment by PCF-Testing** [comment]
I am not very sure the way of language sorting implemented in gh-2390 would solve the original issue. Although such languages as Espanol and Espanol (Argentina) are now grouped together, again - Algerian Arabic is typed out in Latin characters and is located at the top of the list, and general Arabic is typed in Arabic script and placed near the bottom of the list. Rusyn (which is often confused with Russian) is in Latin and in the middle of the list, while Russian is in Cyrillic characters and near the bottom of the list. On the good side, the list is invariant regardless of the UI language, but on the bad side, many very popular languages landed into the bottom section of the list where they are hard to find. I would strongly recommend creating a preview instance for this branch and testing it out with OnDemand and/or real world users before going ahead with merging the branch.

In addition, Sichuan Yi obviously has its name messed up - it contains quadrangular placeholders instead of Unicode characters. Moldavian is mistakenly labeled Romanian (Romania).

Upload subtitles dialog is also broken - language selectors are too wide and spill over beyond the right edge of the dialog.

/api/languages/ on the branch still returns the old style naming of the languages, which is different from the one used in the UI.

**Comment by PCF-Testing** [comment]
![gh-2390](https://cloud.githubusercontent.com/assets/288455/11119188/997363dc-88fc-11e5-94f4-8dfdf8cd8151.png)

**Comment by bendk** [comment]
Okay, I'm building gh-2390.amara.org right now, I would love it if folks looked at it and thought about the changes like you just did.

The rectangles happen when a unicode character is not supported by your font.  I noticed them too.  I guess we should either switch fonts or use roman characters for those languages.  We should also check our fallback fonts and see how those behave.

I think the width of the dialog is determined by the widest lines.  I think we could tweak the display for those.  For example, I noticed that ASL seemed to have a lot of characters.  Maybe we could just list it once and instead of as `<native> - <translated>` which doesn't even make much sense.

**Comment by PCF-Testing** [comment]
Shared the preview link, waiting for end users' feedback on the feature.

**Comment by deanjansen** [comment]
Would it be easy for us to style it more like the Mac language selector (dark native language and lighter translated language), or would that require we do a custom drop-down? 

It's a little less chaotic looking this way:

![image](https://cloud.githubusercontent.com/assets/216145/10671701/1e9a34e4-78ba-11e5-9f67-c78699a60d13.png)

**Comment by bendk** [comment]
It's not possible with a standard select box.  We could do it with a javascript modal or something with a bit of work.

Also I notice that the order in that dialog is really weird.  It's not alphabetical by either the native name, translated name, or language code.  I wonder if they have some special ordering that they hand crafted to be the least surprising.

**Comment by deanjansen** [comment]
Yeah, their ordering is odd – they have so few languages compared to us... 

A styled selector would be awesome, but sounds like it's probably a separate feature.

**Comment by PCF-Testing** [comment]
Feedback from Jenny:

1. The proposed language selection is difficult to parse because of the dual language names on each line. And it's a bit confusing when a language is represented twice the same way, i.e. "Algerian Arabic - Algerian Arabic".  

Recommendation: only list a language once, in its native script. This will make it easier for speakers of the language to zero in on what they're looking for.

2. Many of the most commonly selected languages appear at the very bottom of the dropdown, i.e. Arabic, Chinese, Japanese, Korean, Russian, etc. Because the language list is so long, the problem is exacerbated.

Recommendation: list the most popular languages at the top.

Here are a few threads with more info about these methods:
http://ux.stackexchange.com/questions/17064/how-do-you-sort-a-list-of-languages
http://stackoverflow.com/questions/3637341/is-there-a-proper-order-for-listing-languages

**Comment by bendk** [comment]
Unfortunately, we can't simply show native languages because we support so many.  We're using the babel library which gets its data from the unicode CLDR dataset, but still some of our languages don't have translated entries.

There wasn't agreement on if we should sort by popularity or not, so I left that out.

What I did do was implement Dean's suggestions for labels which is `[code] - [label]` where label is the native language name if we can get it, otherwise it's the translated name from gettext.

One last thought I had about this was removing the selectboxes altogether.  I don't think they have a great UI with so many entries.  What if we did something similar to user search, where you start typing, then we display a list of languages that match the query?  We could match on code, native name and translated name.  I like this because:
  - I almost always end up typing anyways to find the entry
  - If there are similar languages, we'll probably show them all together regardless of the ordering.
  - No need to scan through lots of languages that you've never heard of

**Comment by PCF-Testing** [comment]
I really like the idea of replacing the drop-downs with search tools - with this, we can stop worrying about the length of the list (the total number of existing languages is around 6,000).

A couple of things to consider in this case:

- Make search match by combination anywhere in entry (so that "Arabic" would return "Arabic", "Algerian Arabic", and "Tunisian Arabic")

- Will users need to always switch to English when typing in the language name? They might be using other languages by default

**Comment by bendk** [comment]
So I made 2432 for the search tool and other super-nice improvements.  Let's keep this ticket focused on improving the basics and getting things working well for TED.  It would be very difficult to do the more advanced stuff with old-style teams anyways.  I just pushed a couple changes that make the select about as good as it can get:

 - Label languages as `Native Name [code]`  If the native name is not available, we use the translated name for the user's current language.
  - Put the most popular languages as a group at the top of the list.

**Comment by PCF-Testing** [comment]
Generally, I really like how languages are arranged in the list now. In my opinion, this version is the best we've had so far. This order makes the most frequent languages quick and easy to find, and encourages users to look well for the desired language in the full array of supported languages.

Some problems I can think of immediately:

1. For languages named in non-Latin script or just named very differently from English, we do need to add the English version of the name for the benefit of non-native speakers (for example, think of team admins or AOD PMs). Imagine that a team admin needs to set the video language or create a task / collab for Armenian - in the current version, this is pretty hard to do.

2. How are the top languages selected? It is a bit weird to see localized versions (en-gb and es-mx), as well as Bulgarian, in the top, while such super-popular languages as Hindi, Persian, Indonesian, and Thai are missing.

3. Some pages / dialogs are missing the drop-down. These include Watch / Search pages, Add Task dialog, Language filters in old-style team, Create Pro-Requests dialog. Pro-Request Queue page has a mix of regular and new-fashioned language names.

4. Until the improved language pick tool is out, we'll need to help users navigate the new language list by posting the full list of supported languages with English equivalents and ISO codes on a page. If posting such page directly on the site is too much work, then I can place one on the support site, but we may want to hyper-link that page somewhere in the UI to make it more visible.

**Comment by PCF-Testing** [comment]
Cannot publish a subtitle in old-style team (with or without tasks) on the branch. The user sees an error message in the editor, in the logs the error is as follows:

app_1    | INFO 2015-12-05 08:04:11,833 signals 9 140194636359424 notification: subs-approved (version: SubtitleVersion 228 / RwkALnHicEs6 / Spanish v5)
app_1    | ERROR 2015-12-05 08:04:11,845 base 9 140194636359424 Internal Server Error: /api/videos/RwkALnHicEs6/languages/es/subtitles/
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1    |     response = callback(request, *callback_args, **callback_kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
app_1    |     return view_func(*args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 48, in view
app_1    |     return self.dispatch(request, *args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
app_1    |     response = self.handle_exception(exc)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
app_1    |     response = handler(request, *args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py", line 260, in post
app_1    |     return self.create(request, *args, **kwargs)
app_1    |   File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 690, in create
app_1    |     **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
app_1    |     self.perform_create(serializer)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
app_1    |     serializer.save()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 164, in save
app_1    |     self.instance = self.create(validated_data)
app_1    |   File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 616, in create
app_1    |     origin=origin)
app_1    |   File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 550, in add_subtitles
app_1    |     action.perform(author, video, version.subtitle_language, version)
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/subtitleworkflows.py", line 99, in perform
app_1    |     _publish_subtitles_if_needed(subtitle_language, saved_version)
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/subtitleworkflows.py", line 45, in _publish_subtitles_if_needed
app_1    |     subtitles_published.send(subtitle_language, version=version)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 172, in send
app_1    |     response = receiver(signal=self, sender=sender, **named)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/billing/signalhandlers.py", line 13, in on_subtitles_published
app_1    |     BillingRecord.create_for_published_subtitles(sender, version, job_id)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/billing/models.py", line 68, in create_for_published_subtitles
app_1    |     tv.team, video, language, job_id)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/billing/calc_data.py", line 122, in calc_billing_record_data
app_1    |     provider_request = collab.provider_request
app_1    | AttributeError: 'NoneType' object has no attribute 'provider_request'
worker_1 | [2015-12-05 08:04:11,942: INFO/MainProcess] Finished 'http://172.17.1.162:8983/solr/update/?commit=true' (POST) with body '<add><doc>' in 0.891 seconds.

**Comment by bendk** [comment]
1) Maybe we should just go back to using the translated language after all.  (does this cover 4 as well?)

2) I tried to count the number of languages with completed subtitles.  I think I did the query right, but I may have gotten in wrong.

3) I'll add those those.

**Comment by bendk** [comment]
I took a look at the language drop downs you listed.  The watch/search pages, add task, and old-style language filters are really different and it would be hard to change them.  I think we're okay keeping them how they are, especially since TED didn't seem to mind them too much.

I fixed the create pro-request dialog, it wasn't really working at all.

I couldn't figure out the issue you were talking about with the provider queue page, it seemed to work fine for me.

**Comment by bendk** [comment]
@deanjansen what do you think about going away from native names and back to names in the user's language?

**Comment by deanjansen** [comment]
Seems good to me, especially since this is for legacy selectors.

**Comment by bendk** [comment]
Okay, I just went with that change.  BTW, there's now a branch on amara-enterprise that you need as well.

So I think the last question is what languages to list in the popular section?  Should I try to calculate them a different way?  Should we just pick a handful?

**Comment by PCF-Testing** [comment]
Drop-down on the latest version of the branch:

![gh-2390_language_list](https://cloud.githubusercontent.com/assets/288455/11842240/32bd5d2a-a3b7-11e5-80b3-43bd18c736cc.png)

Language lists for Watch / Search pages, Add Task dialog, Language filters in old-style team are still missing and need to be fixed.

The mixup of languages on /providers/queues/ page is displayed on the screenshot below. It was looking messier in the previous version - just note the difference in Accounts and Languages tables.

![gh-2390_language_list](https://cloud.githubusercontent.com/assets/288455/11842353/021d8aea-a3b8-11e5-9c5f-9747cf51305d.png)

Do we want to demo this new version of the language list to TED on a preview?

**Comment by bendk** [comment]
I'm deploying a preview now.  It should be ready at gh-2390.amara.org in 30-60 minutes.

**Comment by PCF-Testing** [comment]
Shared the link to the preview instance.

**Comment by PCF-Testing** [comment]
Looks like this version has received an approval: http://support.amara.org/helpdesk/tickets/80147

Jenny would like to have the popular languages sorted by language code for consistency with the general list of languages.

I plan to add a FreshDesk help page listing all Amara languages to help users search and navigate it. Shall we place a link to this page somewhere in the UI, e.g in Add New Language dialog, to make it more visible?

Also, a reminder that language selectors are still missing in several places on the branch and need to be fixed before the branch can be merged.

**Comment by deanjansen** [comment]
Maggie suggests this list: https://en.wikipedia.org/wiki/Languages_used_on_the_Internet as a basis for the popular languages. With .3% as the cutoff, which would include the top 24, plus both major Chinese variants (zh-cn and zh-tw) and both major Portuguese variants (pt and pt-br) for a total of 26 popular languages.

**Comment by bendk** [comment]
Just pushed an update to the popular language section.

Where are the places where we need to change the langauge selectors?  If I recall correctly, I think a lot of them were using special selectboxes.

I think the important thing for this issue is to make sure we use this selector whenever the user is selecting their languages.  For other selectboxes, I think it could be good to use it, but it's not a requirement.

**Comment by PCF-Testing** [comment]
I cannot start the branch locally (see the error message below), but the language selectors were missing in the following places - search tool on Watch / Search pages, Add Task dialog on old style team Tasks for a Video page, Language filters in old-style team, Create Pro-Requests dialog.

Attaching to unisubs_worker_1, unisubs_app_1
worker_1 | deploy/create_commit_file must be ran before boostrapping djangoINFO 2016-02-05 07:08:58,064 base 1 139665835759424 Raven is not configured (logging is disabled). Please see the documentation for more information.
worker_1 | Traceback (most recent call last):
worker_1 |   File "manage.py", line 37, in <module>
worker_1 |     startup.startup()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 68, in startup
worker_1 |     run_startup_modules()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
worker_1 |     __import__('%s.startup' % app)
worker_1 |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
worker_1 |     import teams.workflows.startup
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
worker_1 |     from teams.workflows.old import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
worker_1 |     from .workflow import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
worker_1 |     from teams import views
worker_1 |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
worker_1 |     from teams.forms import (
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
worker_1 |     class MoveTeamVideoForm(forms.Form):
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
worker_1 |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
worker_1 |     return self.get_query_set()
worker_1 |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
worker_1 |     return TeamQuerySet(Team).filter(deleted=False)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
worker_1 |     return self._filter_or_exclude(False, *args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
worker_1 |     clone.query.add_q(Q(*args, **kwargs))
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
worker_1 |     can_reuse=used_aliases, force_having=force_having)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
worker_1 |     process_extras=process_extras)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
worker_1 |     field, model, direct, m2m = opts.get_field_by_name(name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
worker_1 |     cache = self.init_name_map()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
worker_1 |     for f, model in self.get_all_related_m2m_objects_with_model():
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
worker_1 |     cache = self._fill_related_many_to_many_cache()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
worker_1 |     for klass in get_models(only_installed=False):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
worker_1 |     self._populate()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 67, in _populate
worker_1 |     self.load_app(app_name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
worker_1 |     models = import_module('.models', app_name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
worker_1 |     __import__(name)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/prorequests/models.py", line 37, in <module>
worker_1 |     from vimeo.videos import make_vimeo_pro_request_video, make_vimeo_user_video
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/vimeo/videos.py", line 27, in <module>
worker_1 |     from vimeo.team import get_vimeo_team
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/vimeo/team.py", line 8, in <module>
worker_1 |     from utils.test_utils.plugin import test_case_complete
worker_1 | ImportError: cannot import name test_case_complete
app_1    | deploy/create_commit_file must be ran before boostrapping djangoINFO 2016-02-05 07:08:59,212 base 1 140231883753280 Raven is not configured (logging is disabled). Please see the documentation for more information.
app_1    | Traceback (most recent call last):
app_1    |   File "manage.py", line 37, in <module>
app_1    |     startup.startup()
app_1    |   File "/opt/apps/unisubs/startup.py", line 68, in startup
app_1    |     run_startup_modules()
app_1    |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
app_1    |     __import__('%s.startup' % app)
app_1    |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
app_1    |     import teams.workflows.startup
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
app_1    |     from teams.workflows.old import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
app_1    |     from .workflow import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
app_1    |     from teams import views
app_1    |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
app_1    |     from teams.forms import (
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
app_1    |     class MoveTeamVideoForm(forms.Form):
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
app_1    |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
app_1    |     return self.get_query_set()
app_1    |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
app_1    |     return TeamQuerySet(Team).filter(deleted=False)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
app_1    |     return self._filter_or_exclude(False, *args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
app_1    |     clone.query.add_q(Q(*args, **kwargs))
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
app_1    |     can_reuse=used_aliases, force_having=force_having)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
app_1    |     process_extras=process_extras)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
app_1    |     field, model, direct, m2m = opts.get_field_by_name(name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
app_1    |     cache = self.init_name_map()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
app_1    |     for f, model in self.get_all_related_m2m_objects_with_model():
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
app_1    |     cache = self._fill_related_many_to_many_cache()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
app_1    |     for klass in get_models(only_installed=False):
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
app_1    |     self._populate()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 67, in _populate
app_1    |     self.load_app(app_name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
app_1    |     models = import_module('.models', app_name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
app_1    |     __import__(name)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/prorequests/models.py", line 37, in <module>
app_1    |     from vimeo.videos import make_vimeo_pro_request_video, make_vimeo_user_video
app_1    |   File "/opt/apps/unisubs/amara-enterprise/vimeo/videos.py", line 27, in <module>
app_1    |     from vimeo.team import get_vimeo_team
app_1    |   File "/opt/apps/unisubs/amara-enterprise/vimeo/team.py", line 8, in <module>
app_1    |     from utils.test_utils.plugin import test_case_complete
app_1    | ImportError: cannot import name test_case_complete
unisubs_worker_1 exited with code 1
unisubs_app_1 exited with code 1

**Comment by bendk** [comment]
I just merged and pushed an update I think it can startup.  I did some changes for the language selectors:

- For all of them, I tried to make them use the `Language Name [code]` format
- For the filters on the team videos and move videos pages, I added the popular section
- For the filters on the search/watch page and the task create page, I fixed some bugs but didn't implement the popular section.  There are some issue here with how things are implemented that make it a bit tricky.  I would like to just wait and let new-style team pages replace the tasks page and create a new-style search/watch page as part of the upcoming UI work.
- The create Pro-Requests dialog only allows you to select languages that are actually available for the pro-request.  I think the list should generally be pretty small, so I don't think we need the popular section.  I did fix a bug and make it follow the new format though in the gh-2390 branch on amara-enterprise.

**Comment by PCF-Testing** [comment]
Found an issue with sorting languages in All section of the list - two most recently used languages are at the top of the list breaking the sorting:

![oldteamfilervideosbylanguage](https://cloud.githubusercontent.com/assets/288455/12864291/f8110422-cc3a-11e5-8755-19e8380951db.png)

What I did was:
- Submit a video, label it as zh-cn and subtitle in zh-cn
- Submit a video, label it as en, upload en subtitles and add to TEDxTalks proect
- Check the Language filter on Team Videos page

**Comment by PCF-Testing** [comment]
On Move Videos page for old style teams the filter for Primary Audio Language does not keep up the selected value after Update button is clicked. If Language filter on the same page has a non-default value, Primary Audio Language filter gets the same value.

Steps:
1. Open team videos page, click Move Videos.
2. Expand Filter and Sort panel.
3. Select some language from Language drop-down, click Update.
4. Select some language from Primary Audio Language drop-down, click Update.

**Comment by bendk** [comment]
I can't reproduce that issue with the order of the list.  Can you give me detailed steps to do it?  Couple questions about that:
  - Is this a tasks team or a non-tasks team?
  - When you say label the video with a language, is this setting the primary audio language?  Is it changing the title?

**Comment by bendk** [comment]
I wasn't able to reproduce the issues with the extra "----" fields.  I suspect it might be a caching issue.  Maybe try running `dev manage clear_cache`.

I also wasn't able to reproduce the pro-request issue.  I'm guessing that's a separate thing and has to do with how the tables get set up.

**Comment by PCF-Testing** [comment]
After pulling in the latest changes and rebuilding the branch from clean slate (bin/dev build, bin/dev dbreset), could reproduce the issue with messed up full language list:
1. Submitted a video.
2. Started subtitling - primary language zh-cn, subtitling in - zh-cn.
3. Added a few lines and saved a draft.
4. Opened Watch page and tried to search for videos in a certain original language - zh-cn was at the top of the list. In the list of subtitle languages zh-cn was also at the top.
5. Created "TED" team, opened Team Videos page, checked has language filter - zh-cn was at the top.

A similar thing happens if in step 2 the video is in a different language, e.g. Russian - this language gets to the top of the list.

Adding more videos/languages does not seem to affect the list any further.

**Comment by PCF-Testing** [comment]
Also, the following two tests are broken on the branch:

======================================================================
ERROR: test_subtitle_language_filter (videos.tests.test_forms.CreateSubtitlesFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/videos/tests/test_forms.py", line 162, in test_subtitle_language_filter
    set(self.make_form()['subtitle_language_code'].field.choices),
TypeError: unhashable type: 'list'

======================================================================
ERROR: test_subtitle_language_order (videos.tests.test_forms.CreateSubtitlesFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/videos/tests/test_forms.py", line 142, in test_subtitle_language_order
    language_choices_ordered('es', 'fr'))
  File "/opt/apps/amara/apps/videos/tests/test_forms.py", line 135, in language_choices_ordered
    rv.append((code, choice_map.pop(code)))
KeyError: 'es'

Other than that, there seem to be no problems - but since the branch was launched with a clean database, there was very, very little data to test with. Is it possible to get a preview instance, or the only option to try the new selector with extended data is to merge and deploy staging?

**Comment by bendk** [comment]
Ahh, I get the language sorting issue now.  On the search page, we order the list based on the number of subtitles.  I think that's okay to keep for now.  The issue was that that ordering was getting kept for other language selectors which is wrong.  There was code to prevent that, but it wasn't working after the list got the optgroups.  I think it should be working now.

**Comment by bendk** [comment]
I'm fixing the test issues now.  The actually point to a couple issues with the create subtitles forms:
  - After the changes, we weren't properly excluding languages that already have subtitles.  This should be fixed now
  - Before the changes we listed the user's languages at the top of the list.  That doesn't make much sense anymore.  For now I'm going to stick with just listing the popular languages at the top.  But does it make sense to change that so the top section is the user's languages?  If so, should we change any other dialogs to work like that?

I'll try to get a preview deployed with this.  Still need to work on the ops script to make that possible though.

**Comment by PCF-Testing** [comment]
> does it make sense to change that so the top section is the user's languages?

Having the user's languages at the top of the list is really nice, but if making the change is time-consuming and can introduce more bugs, I'd say we are OK without it, given that the code-sorted selector is temporary and will be replaced with a language look-up tool in the future.

**Comment by bendk** [comment]
Okay, I went ahead and updated the form on the create subtitles page.

**Comment by PCF-Testing** [comment]
The selector in the form looks absolutely amazing! Love it totally.

On other pages, selectors seem to behave well and no longer show the frequently used (zh-cn and ru) languages on the top of the All section.

3 tests failed:

======================================================================
ERROR: test_short_url (videos.tests.test_template_tags.ShortUrlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/videos/tests/test_template_tags.py", line 54, in test_short_url
    response = self.client.get(self.short_url, follow=True)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 441, in get
    response = self._handle_redirects(response, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 560, in _handle_redirects
    response = self.get(url.path, QueryDict(url.query), follow=False, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/apps/amara/apps/videos/decorators.py", line 60, in wrapper
    return func(request, video, *args, **kwargs)
  File "/opt/apps/amara/apps/videos/views.py", line 323, in video
    context = VideoPageContext(request, video, video_url, tab, workflow)
  File "/opt/apps/amara/apps/videos/views.py", line 239, in __init__
    request, video, request.POST or None)
  File "/opt/apps/amara/apps/videos/forms.py", line 373, in __init__
    super(CreateSubtitlesForm, self).__init__(request, data=data)
  File "/opt/apps/amara/apps/videos/forms.py", line 307, in __init__
    self.setup_subtitle_language_code()
  File "/opt/apps/amara/apps/videos/forms.py", line 324, in setup_subtitle_language_code
    field.choices = sorted(self.get_language_choices(), key=sort_key)
  File "/opt/apps/amara/apps/videos/forms.py", line 380, in get_language_choices
    user_language_choices = self.user.get_language_codes_and_names()
AttributeError: 'AnonymousUser' object has no attribute 'get_language_codes_and_names'

======================================================================
ERROR: test_history (videos.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/videos/tests/test_views.py", line 226, in test_history
    [self.video.video_id, sl.language_code, sl.id])
  File "/opt/apps/amara/apps/videos/tests/videotestutils.py", line 97, in _simple_test
    response = self.client.get(reverse(url_name, args=args, kwargs=kwargs), data)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/apps/amara/apps/videos/decorators.py", line 42, in wrapper
    return func(request, video, *args, **kwargs)
  File "/opt/apps/amara/apps/videos/views.py", line 626, in language_subtitles
    context = ContextClass(request, video, lang, lang_id, version_id)
  File "/opt/apps/amara/apps/videos/views.py", line 467, in __init__
    request, video, request.POST or None)
  File "/opt/apps/amara/apps/videos/forms.py", line 373, in __init__
    super(CreateSubtitlesForm, self).__init__(request, data=data)
  File "/opt/apps/amara/apps/videos/forms.py", line 307, in __init__
    self.setup_subtitle_language_code()
  File "/opt/apps/amara/apps/videos/forms.py", line 324, in setup_subtitle_language_code
    field.choices = sorted(self.get_language_choices(), key=sort_key)
  File "/opt/apps/amara/apps/videos/forms.py", line 380, in get_language_choices
    user_language_choices = self.user.get_language_codes_and_names()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 185, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'get_language_codes_and_names'

======================================================================
ERROR: test_video (videos.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/videos/tests/test_views.py", line 202, in test_video
    response = self.client.get(self.video.get_absolute_url(), follow=True)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/apps/amara/apps/videos/decorators.py", line 60, in wrapper
    return func(request, video, *args, **kwargs)
  File "/opt/apps/amara/apps/videos/views.py", line 323, in video
    context = VideoPageContext(request, video, video_url, tab, workflow)
  File "/opt/apps/amara/apps/videos/views.py", line 239, in __init__
    request, video, request.POST or None)
  File "/opt/apps/amara/apps/videos/forms.py", line 373, in __init__
    super(CreateSubtitlesForm, self).__init__(request, data=data)
  File "/opt/apps/amara/apps/videos/forms.py", line 307, in __init__
    self.setup_subtitle_language_code()
  File "/opt/apps/amara/apps/videos/forms.py", line 324, in setup_subtitle_language_code
    field.choices = sorted(self.get_language_choices(), key=sort_key)
  File "/opt/apps/amara/apps/videos/forms.py", line 380, in get_language_choices
    user_language_choices = self.user.get_language_codes_and_names()
AttributeError: 'AnonymousUser' object has no attribute 'get_language_codes_and_names'

And one last nitpick - could the pick tool for preferred languages (both in old-style task-based teams and in new teams) have just one section, All, so that a language could not be picked twice? Is it hard to change? Everything else looks just terrific.

**Comment by bendk** [comment]
Okay, just pushed 1 more set of commits to both unisubs and amara-enterprise.  I think this should be all set now.

**Comment by PCF-Testing** [comment]
Beautiful! Making PRs for both repos.

**Comment by PCF-Testing** [comment]
Deployed.
