### ISSUE TITLE
Update user menu header

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2944]
Right now it's the user's full name in upper case.

It should be the username without changing the case.

**Comment by bendk** [comment]
I pushed this one directly to staging.

**Comment by kslottow** [comment]
AWESOME! thanks @bendk

**Comment by PCF-Testing** [comment]
Verified. Moving to Waiting for Deploy.

**Comment by PCF-Testing** [comment]
@bendk: on staging.amara.org, the marketing pages still have the username in uppercase. App pages display it matching the case.

**Comment by PCF-Testing** [comment]
Deployed.
