### ISSUE TITLE
Ghost subtitle in the timeline

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3032]
See the subtitle on the far right in the image below.  I'm not sure why it gets there, but it's weird.  The text also doesn't seem to change when the text in the subtitles list changes.

![image](https://user-images.githubusercontent.com/1012809/33328352-c6a37d9c-d427-11e7-86ee-94d7b71c2798.png)

**Comment by PCF-Testing** [comment]
That is "on-deck" subtitle - the next one after the one being synced. The text actually changes as you sync subtitles, but only the end of the whole subtitle is visible. If you try with longer sentences, you should be able to see the text in on-deck subtitle change.

**Comment by bendk** [comment]
Ahh, that's what I thought it was at first, but then a couple issues made me think it was something different:

 - If you edit the for that subtitle in the subtitle list, the text doesn't change on the timeline
 - When I seek between the unsynced part of the timeline and the last synced subtitles, the "to-be-synced" subtitle and the "on-deck" subtitle change in ways that feel really unintuitive to me.  I think we can do something to make this process clearer.

**Comment by bendk** [comment]
Fixed in gh-3032

**Comment by bendk** [comment]
I think I meant to say gh-3023, which already was merged.  Can you test if it's an issue in dev?

**Comment by PCF-Testing** [comment]
Checked on dev branch locally.

- [x] The style looks different then other subtitles and you can't see the first few characters of the subtitle

It still looks dimmed, in contrast to the other subtitles (which seems correct to me). All the characters (at least, at the beginning of the sentence) are visible now, as seen on the screenshot below:

![screenshot from 2018-05-08 01 28 35](https://user-images.githubusercontent.com/288455/39746588-955e0c0a-525f-11e8-838e-b17c6ac8cd31.png)

- [x] If you edit the text in the subtitle list, it doesn't change in the timeline
The changes to the text are reflected not in the real time as the user is typing, but once the edits are applied, i.e. after the user presses ENTER key or clicks outside of the subtitle cell that is being edited. I believe this is the correct behavior, so marking the item as resolved.

- [ ] If on-deck subtitle is going to be placed, it appears at the current time. If you then move the subtitle before it so that it occupies the time, then the on-deck subtitle disappears. Once you start playback, or seek, it reappears.

I am not sure I understand this one well. Suppose we have the following set of untimed subtitles:
AAA
BBB
CCC
If "AAA" is already synced, "BBB" is in progress (with the start time set but end time still unknown), the video is playing, "CCC" is on deck. What happens next, what subtitle is moved and where?

![3032](https://user-images.githubusercontent.com/288455/39748545-3496285c-5265-11e8-9889-e06e62c39bf1.jpg)

**Comment by bendk** [comment]
From that situation, I believe you would hit the bug with the following actions:
  - Make sure playback is stopped
  - Hit up to set the end time for BBB
  - Seek 1 second later.
  - You should see CCC positioned on the timeline, starting at the current time
  - Drag the end time for BBB 2 seconds forward

The bug was that CCC then totally disappeared from the timeline.  It wasn't even in that right, shaded, area.

**Comment by PCF-Testing** [comment]
When I follow this scenario, I still see CCC totally disappear after dragging the end time for BBB. This happens on production and on dev alike. When I press TAB next to play the video, CCC re-appears on the far right as an on-deck subtitle, and once the video plays past the end time for BBB, CCC becomes displayed near the timeline cursor as a regularly styled subtitle.

Does this mean that this issue still needs to be fixed, or was the original problem that CCC failed to re-appear when the video started playing again?

**Comment by bendk** [comment]
You're right, it's happening and it's still an issue.
