### ISSUE TITLE
Update message hiding code

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3059]
Right now the code handles this by setting a cookie and using that to hide the messages.  That's not great, since in the caching code we want to avoid sending cookies if we can.  Instead, I think we should handle it like this:

 - Add a last_hidden_message field to CustomUser
 - When the user clicks the hide link/button, then we do the following:
   - Hide the div we're displaying to the user
   - Make a POST request, that updates the last_hidden_message field.
- When we're rendering the messages code, we use the field, rather than the cookie.

**Comment by kslottow** [comment]
awesome, should we close this @bendk ?

**Comment by bendk** [comment]
This needs to be a 2 phase deploy, the first phase will save the cookie value, then the second phase will start using it.  To test:

 - Run gh-3059-stage1
    - create 2 users.  I'll call them user1 and user2
    - send a message from user2 to user1
    - open up page with user1.  Hide the new messages alert 
    - Send a second message from user2 to user1
    - Open up a page with user1, don't hide the new messages 
 - Run gh-3059-stage2
    - Open up a page with user1.  You should see "1 new messages"
    - Hide the message box
    - Open up a page again, you should not see the new message alert

**Comment by PCF-Testing** [comment]
Exception on gh-3059-stage1 at http://unisubs.example.com:8000:

AttributeError at /
'AnonymousUser' object has no attribute 'check_last_hidden_message_id'
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/
Django Version:	1.4.22
Exception Type:	AttributeError
Exception Value:	
'AnonymousUser' object has no attribute 'check_last_hidden_message_id'
Exception Location:	/opt/apps/amara/apps/auth/middleware.py in get_user, line 33

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _cache_controlled
  75.             response = viewfunc(request, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/vary.py" in inner_func
  19.             response = func(*args, **kwargs)
File "/opt/apps/amara/amara-enterprise/marketing/views.py" in home
  43.         'data': get_data(),
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py" in render
  40.         context_instance = RequestContext(request, current_app=current_app)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/templates/panel.py" in _request_context__init__
  55.         context = processor(request)
File "/opt/apps/amara/utils/context_processors.py" in user_languages
  52.         'USER_LANGUAGES': get_user_languages_from_request(request)
File "/opt/apps/amara/utils/translation.py" in get_user_languages_from_request
  165.     if request.user.is_authenticated():
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in inner
  184.             self._setup()
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in _setup
  248.         self._wrapped = self._setupfunc()
File "/opt/apps/amara/apps/auth/middleware.py" in <lambda>
  64.         request.user = SimpleLazyObject(lambda: get_user(request))
File "/opt/apps/amara/apps/auth/middleware.py" in get_user
  33.         user.check_last_hidden_message_id(request)

Exception Type: AttributeError at /
Exception Value: 'AnonymousUser' object has no attribute 'check_last_hidden_message_id'

**Comment by bendk** [comment]
That one should be fixed now.

**Comment by PCF-Testing** [comment]
For signed in users on gh-3059-stage2:

- [ ] On Home page:

TypeError at /

long() argument must be a string or a number, not 'NoneType'

Request Method: 	GET
Request URL: 	http://unisubs.example.com:8000/en/
Django Version: 	1.4.22
Exception Type: 	TypeError
Exception Value: 	

long() argument must be a string or a number, not 'NoneType'

Exception Location: 	/opt/apps/amara/apps/auth/models.py in check_last_hidden_message_id, line 299
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _cache_controlled
  75.             response = viewfunc(request, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/vary.py" in inner_func
  19.             response = func(*args, **kwargs)
File "/opt/apps/amara/amara-enterprise/marketing/views.py" in home
  43.         'data': get_data(),
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py" in render
  40.         context_instance = RequestContext(request, current_app=current_app)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/templates/panel.py" in _request_context__init__
  55.         context = processor(request)
File "/opt/apps/amara/utils/context_processors.py" in user_languages
  52.         'USER_LANGUAGES': get_user_languages_from_request(request)
File "/opt/apps/amara/utils/translation.py" in get_user_languages_from_request
  165.     if request.user.is_authenticated():
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in inner
  184.             self._setup()
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in _setup
  248.         self._wrapped = self._setupfunc()
File "/opt/apps/amara/apps/auth/middleware.py" in <lambda>
  65.         request.user = SimpleLazyObject(lambda: get_user(request))
File "/opt/apps/amara/apps/auth/middleware.py" in get_user
  34.             user.check_last_hidden_message_id(request)
File "/opt/apps/amara/apps/auth/models.py" in check_last_hidden_message_id
  299.             cookie_value = long(raw_cookie_value)

Exception Type: TypeError at /
Exception Value: long() argument must be a string or a number, not 'NoneType'

- [ ] On /messages/ page:
AttributeError at /messages/
'list' object has no attribute 'get'
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/messages/
Django Version:	1.4.22
Exception Type:	AttributeError
Exception Value:	
'list' object has no attribute 'get'
Exception Location:	/opt/apps/amara/apps/messages/views.py in inbox, line 141
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/messages/views.py" in inbox
  141.         last_message = qs[:1].get()

Exception Type: AttributeError at /messages/
Exception Value: 'list' object has no attribute 'get'

**Comment by bendk** [comment]
I think both of those errors had to be from stage1, the stage2 branch shouldn't have that code anymore.  In any case, it should be fixed.

**Comment by PCF-Testing** [comment]
Exception on gh-3059-stage1, home page:

SyntaxError at /

invalid syntax (views.py, line 144)

Request Method: 	GET
Request URL: 	http://unisubs.example.com:8000/en/
Django Version: 	1.4.22
Exception Type: 	SyntaxError
Exception Value: 	

invalid syntax (views.py, line 144)

Exception Location: 	/opt/apps/amara/apps/messages/urls.py in <module>, line 26

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  99.                             request.path_info)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in resolve
  317.             for pattern in self.url_patterns:
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in url_patterns
  347.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in urlconf_module
  342.             self._urlconf_module = import_module(self.urlconf_name)
File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py" in import_module
  35.     __import__(name)
File "/opt/apps/amara/urls.py" in <module>
  63.         include('messages.urls', namespace='messages')),
File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py" in include
  24.         urlconf_module = import_module(urlconf_module)
File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py" in import_module
  35.     __import__(name)
File "/opt/apps/amara/apps/messages/urls.py" in <module>
  26. from messages.views import rpc_router

Exception Type: SyntaxError at /
Exception Value: invalid syntax (views.py, line 144)

**Comment by bendk** [comment]
Oops, should be fixed now.

**Comment by PCF-Testing** [comment]
I am seeing a weirdness in the following scenario:
- Run gh-3059-stage2
- Open up a page with user1. You should see "1 new messages"
- Hide the message box
- Open up a page again, you should not see the new message alert

If I hide the message box on a marketing page (e.g. home page) by clicking "x" button, this updates th number of the hidden message in the user's profile, but the next time that user views this and other marketing pages (e.g. Volunteer etc.), the message box is still there. It only goes away after refreshing the page. Looks like a caching issue, happens only on the marketing pages (new design messages box), not on old-style pages.

**Comment by bendk** [comment]
Should be fixed.

**Comment by PCF-Testing** [comment]
Fixed for marketing pages and new team pages.

Still does not work on v.1.7 team pages (/activity/, /members/invite/, various /settings/... pages) - if New Messages box is hidden from these pages, the number of the last hidden message does not get updated.

**Comment by bendk** [comment]
Fixed that one.

**Comment by PCF-Testing** [comment]
That's indeed fixed for v.1.7 pages, but no longer works on old-style pages (such as /videos/watch/, /videos/create/, etc.). Sorry, this one seems a bit long-winded...

**Comment by bendk** [comment]
One more try, I think it should be fixed now.

**Comment by PCF-Testing** [comment]
Verified that hiding new messages works as expected on all page types on gh-3059-stage2.

Retried the scenario 2 from https://github.com/pculture/unisubs/issues/3059#issuecomment-356669230 with a small modification - created several unread messages from user2 to user1 while on dev. After switching to gh-3059-stage1, got the following exception:

app_1            | WARNING 2018-02-20 04:39:53,924 auth.models Error reading the hide_new_messages cookie ()
app_1            | Traceback (most recent call last):
app_1            |   File "/opt/apps/amara/apps/auth/models.py", line 301, in check_last_hidden_message_id
app_1            |     cookie_value = long(raw_cookie_value)
app_1            | ValueError: invalid literal for long() with base 10: ''
app_1            | ERROR 2018-02-20 04:39:53,924 unhandled_error local variable 'cookie_value' referenced before assignment
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1            |     response = callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 19, in _wrapped_view
app_1            |     if test_func(request.user):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 42, in <lambda>
app_1            |     lambda u: u.is_authenticated(),
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 184, in inner
app_1            |     self._setup()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 248, in _setup
app_1            |     self._wrapped = self._setupfunc()
app_1            |   File "/opt/apps/amara/apps/auth/middleware.py", line 65, in <lambda>
app_1            |     request.user = SimpleLazyObject(lambda: get_user(request))
app_1            |   File "/opt/apps/amara/apps/auth/middleware.py", line 34, in get_user
app_1            |     user.check_last_hidden_message_id(request)
app_1            |   File "/opt/apps/amara/apps/auth/models.py", line 306, in check_last_hidden_message_id
app_1            |     if cookie_value and cookie_value != self.last_hidden_message_id:
app_1            | UnboundLocalError: local variable 'cookie_value' referenced before assignment
app_1            | INFO 2018-02-20 04:39:54,064 access GET /videos/create/ 500 (1.397s)

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
Same branch (gh-3059-stage1), the following error:

app_1            | ERROR 2018-02-26 20:22:23,914 sentry.errors KeyError('label',)
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/middleware/__init__.py", line 100, in process_view
app_1            |     client.get_transaction_from_request(request)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/client.py", line 304, in get_transaction_from_request
app_1            |     return self.resolver.resolve(request.path)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/resolver.py", line 88, in resolve
app_1            |     match = self._resolve(resolver, path)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/resolver.py", line 66, in _resolve
app_1            |     match = self._resolve(pattern, new_path, parents)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/resolver.py", line 65, in _resolve
app_1            |     if not pattern.callback:
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 217, in callback
app_1            |     self._callback = get_callable(self._callback_str)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 27, in wrapper
app_1            |     result = func(*args)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 93, in get_callable
app_1            |     lookup_view = getattr(import_module(mod_name), func_name)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
app_1            |     __import__(name)
app_1            |   File "/opt/apps/amara/amara-enterprise/taskteammigration/views.py", line 7, in <module>
app_1            |     from taskteammigration import forms
app_1            |   File "/opt/apps/amara/amara-enterprise/taskteammigration/forms.py", line 30, in <module>
app_1            |     class ResultsFiltersForm(FiltersForm):
app_1            |   File "/opt/apps/amara/amara-enterprise/taskteammigration/forms.py", line 37, in ResultsFiltersForm
app_1            |     q = SearchField(required=False)
app_1            |   File "/opt/apps/amara/apps/ui/forms/fields.py", line 182, in __init__
app_1            |     label = kwargs.pop('label')
app_1            | KeyError: 'label'
app_1            | WARNING 2018-02-26 20:22:23,918 auth.models Error reading the hide_new_messages cookie ()
app_1            | Traceback (most recent call last):
app_1            |   File "/opt/apps/amara/apps/auth/models.py", line 301, in check_last_hidden_message_id
app_1            |     cookie_value = long(raw_cookie_value)
app_1            | ValueError: invalid literal for long() with base 10: ''

**Comment by bendk** [comment]
One more fix, sorry for all the back and forth here.

**Comment by PCF-Testing** [comment]
I think it should be good now.

**Comment by PCF-Testing** [comment]
@bendk: I am observing a strange thing on staging
I did not have any recent new messages on my account (maggie_s), so I did not see the banner announcing new messages.
Then I sent a message to that account from another one. This has produced "You have 1 new message", as expected. I closed it from a new teams page by clicking [x] on the banner.
Then I opened another new teams page and got "You have 75736 new messages".
If I close it again and repeat the steps with sending a new message, closing the banner and opening another page, it happens again.

**Comment by bendk** [comment]
Just pushed a change directly to staging that I think should fix this.

**Comment by PCF-Testing** [comment]
Great, does not happen anymore, thanks!

**Comment by PCF-Testing** [comment]
@bendk: after the latest deploy, the code does not work as expected anymore.

You can observe it by impersonating maggie_s on staging.amara.org and trying to dismiss "You have 2 new messages" banner. After clicking [x], the banner still appears on the same and other pages and the last hidden message id remains 2381483.

**Comment by bendk** [comment]
I missed a merge to unisubs, deploying again with that code.

**Comment by PCF-Testing** [comment]
Deployed.
