### ISSUE TITLE
Use a keyboard library to handle shortcuts

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3239]
We're getting more and keyboard shortcuts.  This means the code is getting more complex and there's more chances for bugs.  I think we should move to a library to handle the shortcuts, like this one: https://dmauro.github.io/Keypress/

A couple things this should change:
  - Make all Ctrl shortcuts, work with both Ctrl and Cmd on OSX
  - Make shortcuts only work if the exact modifier combination is pressed.  If you press Ctrl-Alt-Enter, we shouldn't split the current subtitle
  - If there's a dialog open, then ignore all shortcuts.

**Comment by bendk** [comment]
I ended up not going with a library, and instead implementing it ourselves.  I couldn't find a library that checked all these boxes:

 - Able to use `mod` or something similar to mean `ctrl` on windows/linux and `cmd` on mac
 - Ability to have contexts that we can switch on and off.  For example the left/right arrows when you're "nudging" subtitle times, and the up/down arrows when you're in syncing mode.  Some libraries had some support, but they didn't allow you to enable multiple contexts at once, as far as I could tell.
 - Somewhat small

Instead, I wrote a small angular service that seems to work okay.  I copied some code out of mousetrap to make it work.

**Comment by PCF-Testing** [comment]
There is something really wrong with the way the keystrokes are treated in the editor now.

The space bar stops typing/editing a subtitle and starts playing the video. There seems to be no way to actually insert a space between words.

Arrow down and arrow up no longer work to time untimed subtitles.

**Comment by bendk** [comment]
Oops, I fixed that issue with spacebar.

Arrow down and up do set timings, however those are only active during the syncing phase.  Maybe we should rethink these now key bindings since it seems kind of confusing to users who are expecting it to work a certain way.

**Comment by PCF-Testing** [comment]
Just clear the timing on a previously synced set, and you'll find that you cannot sync it anymore.

**Comment by bendk** [comment]
I really think the issue was the up/down arrows were only active during the syncing phase.  I changed the shortcuts so that up/down are always syncs the unsynced subtitle and "s" syncs the nearest start/end time.  I also made it so all these shortcuts are always active.

**Comment by PCF-Testing** [comment]
The problem of Arrow Down/Up buttons not working past the syncing stage is gone now. I believe this change is a definite improvement.

Regarding the use of "s" key for adjusting the subtitle boundaries, I have mixed feelings. On one hand, it is very convenient when you just replay a video with mostly contiguous, not super accurately timed subtitles and adjust the timing without editing the text or introducing gaps between the adjacent subtitles. On the other hand, if you start making edits, try to insert gaps, or have subtitles that are off for more than one second, things stop working that smoothly.

1. Editing text. Consider the following scenario - you are playing the video, press "s" to adjust the timing, then pause (TAB) and click inside a cell and type to correct a typo, then resume (TAB) and press "s" to adjust the timing again. In the latter case, instead of changing the timing, the key changes the text in the subtitle. "s" will work correctly only if you remember to always press ESCAPE after each edit, which is a bit inconvenient.

2. Adjusting the subtitles that are significantly off. Suppose you subtitled a song video and mistakenly pressed ARROW DOWN quite a few beats too early (or on contrary, got distracted and pressed it way too late). If you replay the video and press "s" to correct the mistake, it will silently fail without an explanation. If I expect "s" to work and don't know about the 1 second rule, it seems confusing and might even feel like a bug - maybe a message explaining that the keystroke would not work in this case and drag-dropping on the timeline should be used instead, could help.

3. Gaps between the subtitles. Suppose I (or some collaborator of mine) first roughly synced the subtitles with Arrow Down only, but now I want my subtitles end exactly when the speaker pauses. "s" key does not allow this because it changes both the start time and the end time. Neither can you use arrow buttons to change just one of the two timestamps, so drag-dropping is the only resort. How about adding another shortcut for this, for example, "b" ("beginning") to move just the start time and "e" ("end") for the end time only?

The last thing: ALT+DELETE (deleting the current subtitle), ALT+ARROW UP (navigating up the subtitle set), ALT+ARROW DOWN (navigating down the subtitle set) have stopped working.

**Comment by bendk** [comment]
1 seems like it could be a real problem.  Maybe we should do ctrl-s instead of s.

For 2, we could start by adding a message when it fails.  Then if we get feedback that it's happening a lot, we could increase the range.

Issue 3 is a tough one.  Kenzie and I went back and forth a lot about what to support.  I think the idea was to only support 1 action, since that could be the most user friendly.  But maybe it makes sense to have 3 different ones.  Using `ctrl-[letter]` as the key binding means that we can support many different shortcuts.

@kslottow what do you think about these?

Alt+Delete is now just delete.  No need for the extra key combo -- I think it was only there since we supported undo.  That said, maybe we should still support alt-delete if users have gotten used to it.

I didn't know about alt-up/alt-down.  I'll add those back.

**Comment by PCF-Testing** [comment]
> Alt+Delete is now just delete.

We have already reverted that because it clashed with editing text - instead of removing the character after the cursor, it used to delete the whole subtitle.

**Comment by bendk** [comment]
Delete is still working.  You just need to be out of edit mode.  Press escape, then delete to delete the subtitle.

I think we should add back the other shortcut though, since it allows you to delete subtitles when the edit is active.

But one question I had is about the modifier key.  It seems to me that right now we use both ctrl/cmd and alt for bindings kind of randomly.  I think it would be good to switch to having 1 main modifier key and always using that, unless there's some reason not to.  So what about:

 - ctrl-delete -- delete the subtitle
 - Maybe stay with alt-up and alt-down to navigate the list, since up/down are normally for syncing, but you're using an alternate meaning for them.  I'm really not sure about this though.

**Comment by bendk** [comment]
Based on our conversation I: 
 - Added back alt-up, alt-down
 - Added back alt-del
 - Updated the help window to match the current bindings (I'm pretty sure they all should work)
 - Updated the help window to show either Ctrl, Alt, or Cmd, Option based on user-agent auto-detection.

**Comment by PCF-Testing** [comment]
- [ ] The help panel displays ctrl+s instead of s

- [ ] Browser default shortcuts that should work are listed both for Windows/Linux and for Mac OS X instead of using the user agent detection - is this intentional?

**Comment by bendk** [comment]
So, I'm realizing why we use alt so much.  Almost all ctrl key combinations are used by the browser.  I thought of trying the other letters in sync, but none are usable:

 - ctrl-y is redo
 - ctrl-n is new window
 - ctrl-c is technically not used by browsers, but it's a very common binding for cancel/quit

So, for now I switched it to alt+s.  We should really rethink the shortcuts though.

￼> Browser default shortcuts that should work are listed both for Windows/Linux and for Mac OS X instead of using the user agent detection - is this intentional?

Good point, I fixed that one.

**Comment by PCF-Testing** [comment]
I am still seeing Ctrl+s in the keyboard controls panel if I open a synced transcript for editing.

**Comment by bendk** [comment]
Fixed

**Comment by PCF-Testing** [comment]
A small inconsistency: in Syncing stage, the Keyboard Control panel lists alt+s (alt with lowercase a), and in Review stage it is Alt+s. Alt+s seems to be more consistent with the rest of the in-editor help.

Here we have the same problem as we've discussed earlier for text edits at Syncing stage - if a user pauses and makes a small text edit, she'll be unable to adjust the timing without pressing ESC or TAB (Play) first. I have no idea if users would often need to edit subtitle text and adjust the timing in the same spot - maybe this is not very likely to happen. Should we add a reminder to press ESC to exit the editing mode in this case?

**Comment by bendk** [comment]
I think here we can just make alt+s work during typing.  The issue with up/down was that the user might want to sue that to move around in the textbox.  alt+s doesn't have the same issue.

**Comment by bendk** [comment]
Made alt+s work during typing.

**Comment by PCF-Testing** [comment]
Sorry for repeating the nitpick: in Syncing stage, the Keyboard Control panel lists alt+s (alt with lowercase a) instead of Alt+s.

**Comment by bendk** [comment]
Fixed this one, and also made it display Option + S on mac.

**Comment by PCF-Testing** [comment]
Moving to Holding.

**Comment by bendk** [comment]
Experimental only.

**Comment by PCF-Testing** [comment]
Deployed.
