### ISSUE TITLE
Implement new select list header

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3335]
See: https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b2a8f9a2b7fe16f18869dfd along with the next several comps

We should implement:
 - List title ("Projects")
 - Search bar
 - Add button

Don't implement the filters or list/grid view switcher buttons.

**Comment by asabine** [comment]
@bendk if you want to take a look, the initial work is in https://github.com/pculture/amara-assets/tree/gh-3335 and https://github.com/pculture/unisubs/tree/gh-3335

**Comment by bendk** [comment]
Just pushed some changes that fix the button alignment issues.  I also implemented the slideout on hover.  I think it's easier to do stuff like that with JS, even though I would love to use CSS animations for it.

**Comment by asabine** [comment]
new styleguide entry is under `styleguide/content-header`, used this name instead of select list header since it won't only be used for select lists

**Comment by PCF-Testing** [comment]
- [ ] "+" icon is missing on the Add Item button:

![screenshot from 2018-09-15 08 00 54](https://user-images.githubusercontent.com/288455/45587664-a6b4da00-b8bd-11e8-88d8-735313aa4b94.png)

- [ ] A click on "Add Item" button does not invoke the modal - should it?

- [ ] The search input field is a bit too dark so the black text in it is not easy to read. It matches the mockup in Zeplin, but perhaps a lighter shade of purple would be friendlier to users.

- [ ] If the text in the search field is long, the overflow text overlaps the magnifying glass icon. The text input should end to the left from the icon so that overlapping does not happen. When "Add Item" button expands, the overlapping still should not happen.
![screenshot from 2018-09-15 08 13 14](https://user-images.githubusercontent.com/288455/45587792-ad445100-b8bf-11e8-98fc-9fab9cec60fa.png)

- [ ] In some browser widths (~ 1000-1200 px), "Select List" label wraps to the next line, should it?

**Comment by PCF-Testing** [comment]
White text on the purple background looks unusual but is indeed easier to read. The interaction between the text, magnifying glass and the expanding button works just great.

"+" icon is still missing, there is a rectangular placeholder in its place: https://dev.amara.org/en/styleguide/content-header

**Comment by bendk** [comment]
Yeah, I was wondering if we should do white or dark.  I figured if you're typing in something in the searchbar, then you want it to be highly visible.  Charcoal could work too though.

I'm pushing one more fix for the plus icon, tell me if it fixes things.

**Comment by PCF-Testing** [comment]
Looks beautiful now. Verified.
